from commands import *

config.set_label_references(False)
config.set_hex_dump(True)
config.set_show_autogenerated_labels(False)
config.set_show_cpu_state(False)
config.set_show_char_literals(False)
config.set_show_all_labels(False)

load(0x0e00, "orig/include_binary_file.orig", "6502")

include_binary_file(0x0e05, "orig/include_binary_data.bin", 8)

go()
